sudo: required
services:
 - docker
script:
 - docker build -t lemoncodepracticacloudmarioli .
after_success:
 - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
 - docker tag lemoncodepracticacloudmarioli $DOCKER_USER/lemoncodepracticacloudmarioli
 - docker push $DOCKER_USER/lemoncodepracticacloudmarioli